# Generated by Django 5.2.17 on 2026-09-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(condition=models.Q(('age_min__lte', models.F('age_max'))), name='age_min_lte_age_max'),
        ),
    ]
