# Generated by Django 5.2.17 on 2026-09-24 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_age_min_lte_age_max'),
        ('books', '0002_readingprogress'),
    ]

    operations = [
    ]
